/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhoi;

import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import trabalhoi.Utils;

/**
 *
 * @author Christian
 */
public class Menu extends javax.swing.JDialog {

    /**
     * Creates new form Menu
     */
    public Menu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
                        
        Btn1.setVisible(false);
        Btn2.setVisible(false);
        Btn3.setVisible(false);
        Btn4.setVisible(false);
        Btn5.setVisible(false);
        Btn6.setVisible(false);
        Btn7.setVisible(false);
        Btn8.setVisible(false);
        

        Date now = new Date(System.currentTimeMillis());
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        DataSistema.setText(df.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        NomeEmpresa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NomeUsuario = new javax.swing.JLabel();
        DataSistema = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnCadastros = new javax.swing.JButton();
        BtnLancamentos = new javax.swing.JButton();
        BtnRelatorios = new javax.swing.JButton();
        BtnConfiguracoes = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Btn5 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Empresa:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 10, 10);
        getContentPane().add(jLabel1, gridBagConstraints);

        NomeEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NomeEmpresa.setText("Empresa de Teste Inicial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 15);
        getContentPane().add(NomeEmpresa, gridBagConstraints);

        jLabel3.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 10, 10);
        getContentPane().add(jLabel3, gridBagConstraints);

        NomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NomeUsuario.setText("Acesso Irrestrito");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        getContentPane().add(NomeUsuario, gridBagConstraints);

        DataSistema.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DataSistema.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 15);
        getContentPane().add(DataSistema, gridBagConstraints);

        jLabel6.setText("Data Sistema:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        getContentPane().add(jLabel6, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        BtnCadastros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnCadastros.setText("Cadastros");
        BtnCadastros.setMaximumSize(new java.awt.Dimension(140, 70));
        BtnCadastros.setMinimumSize(new java.awt.Dimension(140, 70));
        BtnCadastros.setPreferredSize(new java.awt.Dimension(140, 70));
        BtnCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickMenu(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel2.add(BtnCadastros, gridBagConstraints);

        BtnLancamentos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnLancamentos.setText("Lançamentos");
        BtnLancamentos.setMaximumSize(new java.awt.Dimension(140, 70));
        BtnLancamentos.setMinimumSize(new java.awt.Dimension(140, 70));
        BtnLancamentos.setPreferredSize(new java.awt.Dimension(140, 70));
        BtnLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickMenu(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel2.add(BtnLancamentos, gridBagConstraints);

        BtnRelatorios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnRelatorios.setText("Relatórios");
        BtnRelatorios.setMaximumSize(new java.awt.Dimension(140, 70));
        BtnRelatorios.setMinimumSize(new java.awt.Dimension(140, 70));
        BtnRelatorios.setPreferredSize(new java.awt.Dimension(140, 70));
        BtnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickMenu(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel2.add(BtnRelatorios, gridBagConstraints);

        BtnConfiguracoes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnConfiguracoes.setText("Configurações");
        BtnConfiguracoes.setMaximumSize(new java.awt.Dimension(140, 70));
        BtnConfiguracoes.setMinimumSize(new java.awt.Dimension(140, 70));
        BtnConfiguracoes.setPreferredSize(new java.awt.Dimension(140, 70));
        BtnConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickMenu(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(BtnConfiguracoes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 10, 15);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        Btn1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn1.setText("Cadastros");
        Btn1.setMaximumSize(new java.awt.Dimension(140, 40));
        Btn1.setMinimumSize(new java.awt.Dimension(140, 40));
        Btn1.setPreferredSize(new java.awt.Dimension(140, 40));
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickMenu(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(Btn1, gridBagConstraints);

        Btn2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn2.setText("Lançamentos");
        Btn2.setMaximumSize(new java.awt.Dimension(140, 40));
        Btn2.setMinimumSize(new java.awt.Dimension(140, 40));
        Btn2.setPreferredSize(new java.awt.Dimension(140, 40));
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickMenu(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(Btn2, gridBagConstraints);

        Btn3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn3.setText("Relatórios");
        Btn3.setMaximumSize(new java.awt.Dimension(140, 40));
        Btn3.setMinimumSize(new java.awt.Dimension(140, 40));
        Btn3.setPreferredSize(new java.awt.Dimension(140, 40));
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickMenu(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(Btn3, gridBagConstraints);

        Btn4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn4.setText("Configurações");
        Btn4.setMaximumSize(new java.awt.Dimension(140, 40));
        Btn4.setMinimumSize(new java.awt.Dimension(140, 40));
        Btn4.setPreferredSize(new java.awt.Dimension(140, 40));
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickMenu(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(Btn4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 10, 15);
        getContentPane().add(jPanel4, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        Btn5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn5.setText("Cadastros");
        Btn5.setMaximumSize(new java.awt.Dimension(140, 40));
        Btn5.setMinimumSize(new java.awt.Dimension(140, 40));
        Btn5.setPreferredSize(new java.awt.Dimension(140, 40));
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickMenu(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel5.add(Btn5, gridBagConstraints);

        Btn6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn6.setText("Lançamentos");
        Btn6.setMaximumSize(new java.awt.Dimension(140, 40));
        Btn6.setMinimumSize(new java.awt.Dimension(140, 40));
        Btn6.setPreferredSize(new java.awt.Dimension(140, 40));
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickMenu(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel5.add(Btn6, gridBagConstraints);

        Btn7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn7.setText("Relatórios");
        Btn7.setMaximumSize(new java.awt.Dimension(140, 40));
        Btn7.setMinimumSize(new java.awt.Dimension(140, 40));
        Btn7.setPreferredSize(new java.awt.Dimension(140, 40));
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickMenu(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel5.add(Btn7, gridBagConstraints);

        Btn8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Btn8.setText("Configurações");
        Btn8.setMaximumSize(new java.awt.Dimension(140, 40));
        Btn8.setMinimumSize(new java.awt.Dimension(140, 40));
        Btn8.setPreferredSize(new java.awt.Dimension(140, 40));
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickMenu(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel5.add(Btn8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 15, 15);
        getContentPane().add(jPanel5, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Metodo generico de todos cliques em botões
     * Executa as ações devidas de acordo com o botão clicado.
     * 
     * Gerencia o Menu do sistema ativando os botões conforme o uso.
     *
     * @param evt evento a ser executado
     */
    private void ClickMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickMenu
        if (evt.getSource() == Btn1 && Btn1.getText().equals("Cidades"))
            {
                CadCidades Cid1 = new CadCidades(new javax.swing.JFrame(), true);
                Cid1.setLocationRelativeTo(this);
                Cid1.setVisible(true);
            }
        if (evt.getSource() == Btn1 && Btn1.getText().equals("Documentos"))
            {
                Documentos Doc1 = new Documentos(new javax.swing.JFrame(), true);
                Doc1.setLocationRelativeTo(this);
                Doc1.setVisible(true);
            }
        if (evt.getSource() == Btn6 && Btn6.getText().equals("Cômodos"))
            {
                CadComodos Com1 = new CadComodos(new javax.swing.JFrame(), true);
                Com1.setLocationRelativeTo(this);
                Com1.setVisible(true);
            }
        if (evt.getSource() == Btn2 && Btn2.getText().equals("Pessoas"))
            {
                CadPessoas Pes1 = new CadPessoas(new javax.swing.JFrame(), true);
                Pes1.setLocationRelativeTo(this);
                Pes1.setVisible(true);
            }
        if (evt.getSource() == Btn3 && Btn3.getText().equals("Produtos"))
            {
                CadProdutos Prd1 = new CadProdutos(new javax.swing.JFrame(), true);
                Prd1.setLocationRelativeTo(this);
                Prd1.setVisible(true);
            }

        Btn1.setVisible(false);
        Btn2.setVisible(false);
        Btn3.setVisible(false);
        Btn4.setVisible(false);
        Btn5.setVisible(false);
        Btn6.setVisible(false);
        Btn7.setVisible(false);
        Btn8.setVisible(false);
        
        Btn1.setText("");
        Btn2.setText("");
        Btn3.setText("");
        Btn4.setText("");
        Btn5.setText("");
        Btn6.setText("");
        Btn7.setText("");
        Btn8.setText("");

        if (evt.getSource() == BtnCadastros)
            {
                Btn1.setText("Cidades");
                Btn2.setText("Pessoas");
                Btn3.setText("Produtos");
                Btn4.setText("Cômodos");
                Btn8.setText("ESC Cancelar");
            }
        if (evt.getSource() == BtnLancamentos)
            {
                Btn1.setText("Documentos");
                Btn2.setText("Reservas");
                Btn3.setText("Pessoas p/Reserva");
                Btn8.setText("ESC Cancelar");
            }
        if (evt.getSource() == BtnRelatorios)
            {
                Btn1.setText("Lista Clientes");
                Btn2.setText("Lista Produtos");
                Btn3.setText("Lista Comodos");
                Btn4.setText("Status de Comodos");
                Btn8.setText("ESC Cancelar");                
            }
        if (evt.getSource() == BtnConfiguracoes)
            {
                Btn8.setText("ESC Cancelar");
                //
            }
        
        if (evt.getSource() == Btn8 && Btn8.getText().equals("ESC Cancelar"))
            {
                Btn8.setText("");
            }
        
        if (!Btn1.getText().isEmpty()) { Btn1.setVisible(true); }
        if (!Btn2.getText().isEmpty()) { Btn2.setVisible(true); }
        if (!Btn3.getText().isEmpty()) { Btn3.setVisible(true); }
        if (!Btn4.getText().isEmpty()) { Btn4.setVisible(true); }
        if (!Btn5.getText().isEmpty()) { Btn5.setVisible(true); }
        if (!Btn6.getText().isEmpty()) { Btn6.setVisible(true); }
        if (!Btn7.getText().isEmpty()) { Btn7.setVisible(true); }
        if (!Btn8.getText().isEmpty()) { Btn8.setVisible(true); }
        
        if (Btn8.isVisible())
            {
                // Menu.setSize(500, 500 );
            }
    }//GEN-LAST:event_ClickMenu

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu dialog = new Menu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton BtnCadastros;
    private javax.swing.JButton BtnConfiguracoes;
    private javax.swing.JButton BtnLancamentos;
    private javax.swing.JButton BtnRelatorios;
    private javax.swing.JLabel DataSistema;
    private javax.swing.JLabel NomeEmpresa;
    private javax.swing.JLabel NomeUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
